# Generated by Django 5.1 on 2025-08-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('national_id', models.CharField(max_length=14)),
                ('valid', models.BooleanField()),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('api_key_used', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
