# Generated by Django 5.1 on 2025-08-15 18:19

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ['-created_at'], 'verbose_name': 'API Key', 'verbose_name_plural': 'API Keys'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Validation Log', 'verbose_name_plural': 'Validation Logs'},
        ),
        migrations.AddField(
            model_name='apikey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this API key was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apikey',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this API key is active'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(db_index=True, help_text='Unique API key for authentication', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='user',
            field=models.CharField(help_text='User identifier associated with this API key', max_length=100),
        ),
        migrations.AlterField(
            model_name='log',
            name='api_key_used',
            field=models.CharField(blank=True, db_index=True, help_text='API key used for this validation', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='error',
            field=models.TextField(blank=True, help_text='Error message if validation failed', null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='extracted_data',
            field=models.JSONField(blank=True, help_text='Extracted data if validation was successful', null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='national_id',
            field=models.CharField(help_text='The national ID that was validated', max_length=14, validators=[django.core.validators.MinLengthValidator(14), django.core.validators.MaxLengthValidator(14)]),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the validation was performed'),
        ),
        migrations.AlterField(
            model_name='log',
            name='valid',
            field=models.BooleanField(help_text='Whether the national ID was valid'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['timestamp', 'valid'], name='api_log_timesta_2bfc0f_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['api_key_used', 'timestamp'], name='api_log_api_key_a13ef7_idx'),
        ),
    ]
