# Generated by Django 5.1 on 2025-08-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_apikey_options_alter_log_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='key',
        ),
        migrations.AddField(
            model_name='apikey',
            name='encrypted_key',
            field=models.TextField(default='placeholder', help_text='Encrypted API key for audit purposes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(db_index=True, default='placeholder', help_text='SHA-256 hash of the API key for lookup', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='api_key_used',
            field=models.CharField(blank=True, db_index=True, help_text='API key preview used for this validation', max_length=8, null=True),
        ),
    ]
