# Generated by Django 5.1 on 2025-08-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_apikey_key_apikey_encrypted_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='key_preview',
            field=models.CharField(default=1111, help_text='Last 4 characters of the API key for display', max_length=4),
            preserve_default=False,
        ),
    ]
