# Generated by Django 5.1 on 2025-08-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_apikey_key_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key_preview',
            field=models.CharField(editable=False, help_text='Last 4 characters of the API key for display (auto-populated)', max_length=4),
        ),
    ]
